branches:
  only:
  - master
  - coverity_scan

language: c

arch:
- amd64
- arm64
- ppc64le
- s390x

compiler:
- gcc
- clang

os:
- linux
- freebsd
- osx

jobs:
  exclude:
  - os: osx
    compiler: gcc
  include:
  - name: 'Linux 32-bit gcc'
    arch: amd64
    compiler: gcc
    os: linux
    env: CFLAGS=-m32
    addons:
      apt:
        packages:
        - gcc-multilib
        - lib32ncurses5-dev
        - libncurses5-dev
        - make
  - name: 'Linux 32-bit clang'
    arch: amd64
    compiler: clang
    os: linux
    env: CFLAGS=-m32
    addons:
      apt:
        packages:
        - gcc-multilib
        - lib32ncurses5-dev
        - libncurses5-dev
        - make
  - name: 'FreeBSD 32-bit gcc'
    arch: amd64
    compiler: gcc
    os: freebsd
    env: CFLAGS=-m32
  - name: 'FreeBSD 32-bit clang'
    arch: amd64
    compiler: clang
    os: freebsd
    env: CFLAGS=-m32

addons:
  apt:
    packages:
    - libncurses5-dev
    - make
  coverity_scan:
    project:
      name: tcsh-org/tcsh
      version: 6.22
      description: C shell with file name completion and command line editing
    notification_email: tcsh-notify@tcsh.org
    build_command_prepend: ./configure
    build_command: make
    # https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan

script: >-
  if [ "${COVERITY_SCAN_BRANCH}" != 1 ] ;
  then ./configure && make && make test ;
  fi
