branches:
  only:
  - master
  - coverity_scan
language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - libncurses-dev
    - make
  coverity_scan:
    project:
      name: tcsh-org/tcsh
      version: 6.22
      description: C shell with file name completion and command line editing
    notification_email: tcsh-notify@tcsh.org
    build_command_prepend: ./configure
    build_command: make
    # https://scan.coverity.com/faq#frequency
    branch_pattern: coverity_scan
jobs:
  exclude:
  - os: osx
    compiler: gcc
arch:
- amd64
- arm64
- ppc64le
- s390x
os:
- linux
- freebsd
- osx
script: >-
  if [ "${COVERITY_SCAN_BRANCH}" != 1 ] ;
  then ./configure && make && make test ;
  fi
