#
# Makefile.ADMIN
#
# Maintenance tasks
#

LYNX=	lynx -dump -nolist
TRIM=	expand | sed -e 's/^  *$//' | cat -s
WEB=	http://www.tcsh.org/page?

.for i in FAQ WishList
$i:
	${LYNX} ${WEB}$i | ${TRIM} > ${.TARGET}
.endfor
