#
# Makefile.ADMIN
#
# Maintenance tasks
#
# You can refetch files from the website, then run "git diff" to
# sanity check any changes before committing.
#

LYNX=	lynx -dump -nolist
TRIM=	expand | sed -e 's/^  *$$//' | cat -s
WEB=	http://www.tcsh.org/page?

PAGES=	FAQ WishList

all: ${PAGES}

.for i in FAQ WishList
$i: force
	${LYNX} ${WEB}$i | ${TRIM} > ${.TARGET}
.endfor

.DUMMY: force
force:
